PR: update contributor & concurrently build of frontend and backend (#4)
Finalgoal231/finalGoal pull request #17
Opened 2024-07-15 09:17 UTC by shinevue

* fix: update contributor

* fix: concurrently build

2024-07-21 13:45 UTC, Johnhvy requested changes

2024-07-21 13:45 UTC, Johnhvy commented on package.json
> +    "start": "concurrently \"npm run dev:frontend\"",
There isn't any command to run concurrently

2024-07-21 13:54 UTC, Johnhvy approved these changes

2024-07-21 13:54 UTC, Johnhvy approved these changes
Good job

2024-07-21 13:59 UTC, shinevue reviewed
Approve

2024-08-06 18:27 UTC, creative2113 approved these changes
Nice job

2024-08-06 18:28 UTC, creative2113 approved these changes
good style code

2024-08-06 18:40 UTC, shinevue reviewed
Thank you

2024-08-06 18:41 UTC, closed without merging