PR: modification of create article page to fix small bug
Finalgoal231/finalGoal pull request #37
Opened 2024-08-18 05:59 UTC by creative2113

please verify this pr and give me a good review.
thank u

2024-08-18 06:07 UTC, shinevue requested changes
Good job
But let's solve this issue

2024-08-18 06:07 UTC, shinevue commented on client/src/components/Input/SelectBoxSmall.js
> +        <option></option>
Why need empty option tag?

2024-08-18 06:07 UTC, shinevue commented on client/src/pages/Article/NewArticle.jsx
> +    if (selected_id.id !== 0 && selected_id.id !== "0") {
When id will be same as "0" of string?

2024-08-18 06:21 UTC, creative2113 reviewed
good style code.

2024-08-18 06:28 UTC, BlackGhost2693 requested changes
Hi, @creative2113 
Good job
Awesome

2024-08-18 06:28 UTC, BlackGhost2693 commented on client/src/components/Input/SelectBoxSmall.js
> +        <option></option>
I think with you

2024-08-18 06:31 UTC, creative2113 reviewed
don't mind

2024-08-18 06:46 UTC, creative2113 commented
> Hi, @creative2113 Good job Awesome

thank you.

2024-08-18 06:46 UTC, creative2113 commented on client/src/components/Input/SelectBoxSmall.js
> +        <option></option>
good idea.

2024-08-18 06:47 UTC, creative2113 reviewed
go ahead

2024-08-18 17:09 UTC, joellake992 requested changes
Change your nickname with Paskal case and no-number

2024-08-18 17:09 UTC, joellake992 commented on README.md
> -#### [ScottKing](https://github.com/creative2113)
Rename your nickname

2024-08-18 17:12 UTC, creative2113 commented on README.md
> -#### [ScottKing](https://github.com/creative2113)
yes, I see.

2024-08-18 17:13 UTC, creative2113 commented on README.md
> -#### [ScottKing](https://github.com/creative2113)
I have changed my nick name.
please check this PR.

2024-08-18 17:15 UTC, creative2113 reviewed
good

2024-08-19 01:47 UTC, shinevue approved these changes
Completed

2024-08-19 01:49 UTC, joellake992 approved these changes
Excellent.

2024-08-19 01:54 UTC, BlackGhost2693 approved these changes
thank you

2024-08-19 01:55 UTC, merged